// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolutionOrders.API.Models.Data;

#nullable disable

namespace SolutionOrders.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260418110047_AddLoginAccounts")]
    partial class AddLoginAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolutionOrders.API.Models.Brand", b =>
                {
                    b.Property<int>("IdBrand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBrand"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBrand");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            IdBrand = 1,
                            Description = "Materiały budowlane do prac remontowych",
                            IsActive = true,
                            Name = "MajsterMix"
                        },
                        new
                        {
                            IdBrand = 2,
                            Description = "Elektronarzędzia dla ekip wykonawczych",
                            IsActive = true,
                            Name = "ProWiert"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategory"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategory");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            IdCategory = 1,
                            Description = "Cement, zaprawy i elementy konstrukcyjne",
                            IsActive = true,
                            Name = "Materiały budowlane"
                        },
                        new
                        {
                            IdCategory = 2,
                            Description = "Narzędzia ręczne, elektronarzędzia i akcesoria",
                            IsActive = true,
                            Name = "Narzędzia i warsztat"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            Address = "ul. Murarska 12, Warszawa",
                            IsActive = true,
                            Name = "Ekipa Remontowa Alfa",
                            Password = "klient.123",
                            PhoneNumber = "500-100-200"
                        },
                        new
                        {
                            IdClient = 2,
                            Address = "ul. Ogrodowa 5, Kraków",
                            IsActive = true,
                            Name = "Dom i Ogród Nowak",
                            Password = "dom.123",
                            PhoneNumber = "600-200-300"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdBrand")
                        .HasColumnType("int");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int?>("IdSupplier")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnitOfMeasurement")
                        .HasColumnType("int");

                    b.Property<int?>("IdWarehouse")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdItem");

                    b.HasIndex("IdBrand");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdSupplier");

                    b.HasIndex("IdUnitOfMeasurement");

                    b.HasIndex("IdWarehouse");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            IdItem = 1,
                            Code = "BUD-CEM-25",
                            Description = "Cement do prac murarskich i remontowych",
                            IdBrand = 1,
                            IdCategory = 1,
                            IdSupplier = 1,
                            IdUnitOfMeasurement = 2,
                            IdWarehouse = 1,
                            IsActive = true,
                            Name = "Cement uniwersalny 25 kg",
                            Price = 29m,
                            Quantity = 120m
                        },
                        new
                        {
                            IdItem = 2,
                            Code = "NAR-WIE-850",
                            Description = "Wiertarka do betonu, cegły i drewna",
                            IdBrand = 2,
                            IdCategory = 2,
                            IdSupplier = 2,
                            IdUnitOfMeasurement = 1,
                            IdWarehouse = 2,
                            IsActive = true,
                            Name = "Wiertarka udarowa 850 W",
                            Price = 249m,
                            Quantity = 18m
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<DateTime?>("DataOrder")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdWorker")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOrder");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdWorker");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.OrderItem", b =>
                {
                    b.Property<int>("IdOrderItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrderItem"));

                    b.Property<int>("IdItem")
                        .HasColumnType("int");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdOrderItem");

                    b.HasIndex("IdItem");

                    b.HasIndex("IdOrder");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Supplier", b =>
                {
                    b.Property<int>("IdSupplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSupplier"));

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSupplier");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            IdSupplier = 1,
                            ContactEmail = "zamowienia@budmat.example",
                            IsActive = true,
                            Name = "BudMat Hurt",
                            PhoneNumber = "700-100-100"
                        },
                        new
                        {
                            IdSupplier = 2,
                            ContactEmail = "kontakt@toolpartner.example",
                            IsActive = true,
                            Name = "ToolPartner",
                            PhoneNumber = "700-200-200"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("IdUnitOfMeasurement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnitOfMeasurement"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUnitOfMeasurement");

                    b.ToTable("UnitOfMeasurements");

                    b.HasData(
                        new
                        {
                            IdUnitOfMeasurement = 1,
                            Description = "Sztuki",
                            IsActive = true,
                            Name = "szt"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 2,
                            Description = "Kilogramy",
                            IsActive = true,
                            Name = "kg"
                        },
                        new
                        {
                            IdUnitOfMeasurement = 3,
                            Description = "Litry",
                            IsActive = true,
                            Name = "l"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Warehouse", b =>
                {
                    b.Property<int>("IdWarehouse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWarehouse"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdWarehouse");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            IdWarehouse = 1,
                            IsActive = true,
                            Location = "Warszawa - Białołęka",
                            Name = "Magazyn główny"
                        },
                        new
                        {
                            IdWarehouse = 2,
                            IsActive = true,
                            Location = "Kraków - Nowa Huta",
                            Name = "Magazyn narzędzi"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Worker", b =>
                {
                    b.Property<int>("IdWorker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWorker"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdWorker");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            IdWorker = 1,
                            FirstName = "Paweł",
                            IsActive = true,
                            LastName = "Administrator",
                            Login = "pawel",
                            Password = "haslo.123"
                        },
                        new
                        {
                            IdWorker = 2,
                            FirstName = "Karolina",
                            IsActive = true,
                            LastName = "Bruk",
                            Login = "kbruk",
                            Password = "pracownik.123"
                        });
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Item", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Brand", "Brand")
                        .WithMany("Items")
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolutionOrders.API.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrders.API.Models.Supplier", "Supplier")
                        .WithMany("Items")
                        .HasForeignKey("IdSupplier")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolutionOrders.API.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Items")
                        .HasForeignKey("IdUnitOfMeasurement")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolutionOrders.API.Models.Warehouse", "Warehouse")
                        .WithMany("Items")
                        .HasForeignKey("IdWarehouse")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Supplier");

                    b.Navigation("UnitOfMeasurement");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Order", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SolutionOrders.API.Models.Worker", "Worker")
                        .WithMany("Orders")
                        .HasForeignKey("IdWorker")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.OrderItem", b =>
                {
                    b.HasOne("SolutionOrders.API.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SolutionOrders.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Brand", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Item", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Supplier", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Warehouse", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SolutionOrders.API.Models.Worker", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
